from __future__ import annotations

import os
from datetime import time
from pathlib import Path


TIMEZONE = "Asia/Kolkata"
STRATEGY_NAME = "TRIGGER_RANGE"
MARKET_OPEN = time(9, 15)
PRETRIGGER_SCAN_START = time(9, 21)
TRIGGER_START = time(9, 30)
LAST_TRIGGER_START = time(9, 36)
MARKET_EXIT = time(15, 15)
SERVICE_STOP = time(15, 20)

QUANTITY = 100
TP1_QUANTITY = 70
RUNNER_QUANTITY = 30
GOLDEN_QUANTITY_MULTIPLIER = 2
GOLDEN_TP1_R_MULTIPLE = 1.3
GOLDEN_TRIGGER_START = time(9, 33)
STANDARD_TP1_TRIGGER_HIGH_FLOOR_FRACTION = 0.0033
ALPHA_REFERENCE_MAX_RANGE = 0.002
BETA_SAME_SLOT_RVOL10_MIN = 0.575
GAMMA_3M_RVOL20_MIN = 0.57
RVOL20_LOOKBACK_BARS = 20
RVOL20_MIN_BARS = 5
SAME_SLOT_RVOL_LOOKBACK_SESSIONS = 10
SAME_SLOT_RVOL_MIN_SESSIONS = 3
TP1_R_MULTIPLE = 3.0
B1_TP1_R_MULTIPLE = 2.0
B1_TIGHT_RANGE_THRESHOLD = 0.001
B1_WIDE_RANGE_THRESHOLD = 0.0035
B1_TIGHT_TP1_R_MULTIPLE = 3.0
B1_WIDE_TP1_R_MULTIPLE = 1.2
MAX_SETUPS_PER_STOCK = 1
G1_SEARCH_CANDLE_COUNT = 3
ENTRY_SEARCH_CANDLE_COUNT = 1
B1_SEARCH_CANDLE_COUNT = 6
B1_ENTRY_CANDLE_COUNT = 1
B1_CONFIRM_CANDLE_COUNT = 3
LARGE_GREEN_RANGE_THRESHOLD = 0.0055
PRETRIGGER_GREEN_MAX_RANGE = 0.0085
TRIGGER_MAX_RANGE = 0.006
TRIGGER_TIGHT_RANGE_THRESHOLD = 0.002
TRIGGER_TIGHT_RANGE_MULTIPLIER = 2.0
TRIGGER_RANGE_THRESHOLD = 0.005
TRIGGER_RANGE_MULTIPLIER = 1.4
TRIGGER_RANGE_ADDEND = 0.001
G1_TIGHT_RANGE_THRESHOLD = 0.0008
G1_WIDE_RANGE_THRESHOLD = 0.003
G1_TIGHT_TP1_R_MULTIPLE = 5.0
G1_MIDDLE_TP1_R_MULTIPLE = 1.3
G1_WIDE_TP1_R_MULTIPLE = 1.5
RANGE_COMPARISON_EPSILON = 1e-12

# Entry-quality tiers. EMA values use completed candles only.
EMA_PERIOD = 20
NORMAL_EMA_3M_LOOKBACK_BARS = 2
NORMAL_EMA_3M_MIN_RISE = 0.0001
SILVER_EMA_1M_LOOKBACK_BARS = 5
SILVER_EMA_1M_MIN_RISE = 0.00116
SILVER_G1_MIN_BODY_FRACTION = 0.579

DATA_DIR = Path("LiveData")
REPORT_DIR = Path("LiveReports")
DATABASE_PATH = DATA_DIR / "scanner930.db"
INSTRUMENT_MASTER_PATH = DATA_DIR / "OpenAPIScripMaster.json"
INSTRUMENT_MASTER_URL = (
    "https://margincalculator.angelone.in/"
    "OpenAPI_File/files/OpenAPIScripMaster.json"
)

# If this project has no local .env, reuse the credentials from the user's
# existing VBOS project. SCANNER_BROKER_ENV can override this on any machine.
REFERENCE_ENV = Path(
    os.getenv(
        "SCANNER_BROKER_ENV",
        r"C:\Users\Admin\Documents\Codex\2026-07-25\he\work"
        r"\VBOS_Backtester\VBOS_Backtester-main\.env",
    )
)

NSE_CASH_EXCHANGE_TYPE = 1
WEBSOCKET_MODE_QUOTE = 2
PRICE_DIVISOR = 100.0
REPORT_REFRESH_SECONDS = 30
DATABASE_FLUSH_SECONDS = 1.0
SINGLE_INSTANCE_PORT = 29330

# Option paper execution. Signals and exits always come from the underlying.
OPTION_PAPER_LOTS = int(os.getenv("OPTION_PAPER_LOTS", "1"))
OPTION_WIDE_STRIKE_MIN_GAP = float(
    os.getenv("OPTION_WIDE_STRIKE_MIN_GAP", "10")
)
OPTION_WIDE_STRIKE_UPPER_THRESHOLD = float(
    os.getenv("OPTION_WIDE_STRIKE_UPPER_THRESHOLD", "0.75")
)
OPTION_MAX_SPREAD_FRACTION = float(
    os.getenv("OPTION_MAX_SPREAD_FRACTION", "0.05")
)
OPTION_MAX_QUOTE_AGE_SECONDS = int(
    os.getenv("OPTION_MAX_QUOTE_AGE_SECONDS", "15")
)
OPTION_TP1_FRACTION = 0.70
OPTION_RUNNER_FRACTION = 0.30
NFO_EXCHANGE_TYPE = 2

# Real cash-equity orders require both command-line confirmation and this
# untracked approval file. Paper mode is always the default.
LIVE_APPROVAL_PHRASE = "LIVE_EQUITY_ORDERS"
LIVE_APPROVAL_FILE = Path("LIVE_APPROVAL.txt")
